_target_: synth_ecg_gen.generator.ECGGenerator

params:
  n_jobs: -1

  output_dir: tmp
  dataset_size: 10

  sample_params:
    leads: 3
    frequency: 24
    duration: 1
    save_duration: 1

  generation_params:
    heart_rate:
      min: 30
      max: 200
      step: 0.1
