output_dir: ???
n_samples: 10

generator:

  _target_: synth_ecg.generator.ECGGenerator

  params:
    n_jobs: -1

    output_dir: ${output_dir}
    n_samples: ${n_samples}

    sample_params:
      leads: 12
      frequency: 24
      duration: 1
      save_duration: 1

    generation_params:
      heart_rate:
        min: 30
        max: 200
        step: 0.1
      perturbations:
        - _target_: synth_ecg.utils.vcg_perturbations.QTElongation.initialize
          ms_forward:
            min: 50
            max: 250
        - _target_: synth_ecg.utils.vcg_perturbations.WideQRS.initialize
          percent_widened:
            min: 100
            max: 1000
          scale:
            min: 0.1
            max: 1
        # qrs_amplitutde:
        #   _target_: synth_ecg.utils.vcg_perturbations.QRSAmplitude.initialize
        #   scale:
        #     min: 0.8
        #     max: 3
        # p_wave_amplitude:
        #   _target_: synth_ecg.utils.vcg_perturbations.PWaveAmplitude.initialize
        #   scale:
        #     min: 2
        #     max: 50
        # t_wave_amplitude:
        #   _target_: synth_ecg.utils.vcg_perturbations.TWaveAmplitude.initialize
        #   scale:
        #     min: 2
        #     max: 10
        # st_change:
        #   _target_: synth_ecg.utils.vcg_perturbations.STChange.initialize
        #   scale:
        #     min: 2
        #     max: 10
